### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by azmeuk** [cxcv/python-tracebackturbo#3]
Hey. I love the idea of having a `traceback` compatible module that shows locals on each frame. Did you consider supporting Python3, or did you lost interest in the project?

**Comment by cxcv** [comment]
Hello Eloi,

interested: yes, time: little.
I think that approach is straight forward: rebase the existing changes to
the latest traceback.py module from python3.
If you want to do so, I'd be happy to integrade a patch.

Cheers
Benjamin

2017-05-10 10:08 GMT+02:00 Éloi Rivard <notifications@github.com>:
